# Docker Compose重写配置文件
# 用于开发环境的特殊配置，不会影响基础的docker-compose.yml

version: '3.8'

services:
  keycloak:
    # 开发环境专用配置
    environment:
      # 启用开发模式功能
      KC_DEV_MODE: true
      # 启用详细日志
      KC_LOG_CONSOLE_FORMAT: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n"
      # 启用调试信息
      KC_SPI_EVENTS_LISTENER_JBOSS_LOGGING_SUCCESS_LEVEL: info
      KC_SPI_EVENTS_LISTENER_JBOSS_LOGGING_ERROR_LEVEL: warn
    
    # 开发环境端口映射
    ports:
      - "8080:8080"
      - "8787:8787"  # 调试端口
    
    # 开发环境卷映射
    volumes:
      - ./realms:/opt/keycloak/data/import:ro
      - ./themes:/opt/keycloak/themes:ro
      - ./logs:/opt/keycloak/data/log
      - keycloak_data:/opt/keycloak/data

  keycloak-db:
    # 开发环境数据库配置
    environment:
      # 启用详细日志
      POSTGRES_LOG_STATEMENT: all
      POSTGRES_LOG_MIN_DURATION_STATEMENT: 0
    
    # 开发环境端口映射
    ports:
      - "5433:5432"
    
    # 开发环境卷映射  
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro

volumes:
  keycloak_postgres_data:
    driver: local
  keycloak_data:
    driver: local
  keycloak_redis_data:
    driver: local