import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { getKcClsx } from "../../login/lib/kcClsx";
export default function LoginOauthGrant(props) {
    const { kcContext, i18n, doUseDefaultCss, classes, Template } = props;
    const { url, oauth, client } = kcContext;
    const { msg, msgStr, advancedMsg, advancedMsgStr } = i18n;
    const { kcClsx } = getKcClsx({
        doUseDefaultCss,
        classes
    });
    return (_jsx(Template, Object.assign({ kcContext: kcContext, i18n: i18n, doUseDefaultCss: doUseDefaultCss, classes: classes, bodyClassName: "oauth", headerNode: _jsxs(_Fragment, { children: [client.attributes.logoUri && _jsx("img", { src: client.attributes.logoUri }), _jsx("p", { children: client.name ? msg("oauthGrantTitle", advancedMsgStr(client.name)) : msg("oauthGrantTitle", client.clientId) })] }) }, { children: _jsxs("div", Object.assign({ id: "kc-oauth", className: "content-area" }, { children: [_jsx("h3", { children: msg("oauthGrantRequest") }), _jsx("ul", { children: oauth.clientScopesRequested.map(clientScope => (_jsx("li", { children: _jsxs("span", { children: [advancedMsg(clientScope.consentScreenText), clientScope.dynamicScopeParameter && (_jsxs(_Fragment, { children: [": ", _jsx("b", { children: clientScope.dynamicScopeParameter })] }))] }) }, clientScope.consentScreenText))) }), client.attributes.policyUri ||
                    (client.attributes.tosUri && (_jsxs("h3", { children: [client.name ? msg("oauthGrantInformation", advancedMsgStr(client.name)) : msg("oauthGrantInformation", client.clientId), client.attributes.tosUri && (_jsxs(_Fragment, { children: [msg("oauthGrantReview"), _jsx("a", Object.assign({ href: client.attributes.tosUri, target: "_blank" }, { children: msg("oauthGrantTos") }))] })), client.attributes.policyUri && (_jsxs(_Fragment, { children: [msg("oauthGrantReview"), _jsx("a", Object.assign({ href: client.attributes.policyUri, target: "_blank" }, { children: msg("oauthGrantPolicy") }))] }))] }))), _jsxs("form", Object.assign({ className: "form-actions", action: url.oauthAction, method: "POST" }, { children: [_jsx("input", { type: "hidden", name: "code", value: oauth.code }), _jsxs("div", Object.assign({ className: kcClsx("kcFormGroupClass") }, { children: [_jsx("div", Object.assign({ id: "kc-form-options" }, { children: _jsx("div", { className: kcClsx("kcFormOptionsWrapperClass") }) })), _jsx("div", Object.assign({ id: "kc-form-buttons" }, { children: _jsxs("div", Object.assign({ className: kcClsx("kcFormButtonsWrapperClass") }, { children: [_jsx("input", { className: kcClsx("kcButtonClass", "kcButtonPrimaryClass", "kcButtonLargeClass"), name: "accept", id: "kc-login", type: "submit", value: msgStr("doYes") }), _jsx("input", { className: kcClsx("kcButtonClass", "kcButtonDefaultClass", "kcButtonLargeClass"), name: "cancel", id: "kc-cancel", type: "submit", value: msgStr("doNo") })] })) }))] }))] })), _jsx("div", { className: "clearfix" })] })) })));
}
//# sourceMappingURL=LoginOauthGrant.js.map